from datetime import datetime

from database.supabase_client import supabase

from backend.resource_workload.workload_cal import (
    calculate_employee_scores,
)


# ==========================================================
# NEW IMPLEMENTATION
# Workload is generated ONLY for the final selected
# Employee -> Task assignment.
# ==========================================================

def generate_employee_workload(
    emp_id,
    task_id,
    similarity_score
):

    # ======================================================
    # OLD IMPLEMENTATION (COMMENTED)
    # ------------------------------------------------------
    # Previously the workload was generated by fetching
    # the latest recommended task from employee_task_match.
    #
    # match = (
    #     supabase
    #     .table("employee_task_match")
    #     .select(
    #         "task_id, similarity_score"
    #     )
    #     .eq("emp_id", emp_id)
    #     .order("created_at", desc=True)
    #     .limit(1)
    #     .single()
    #     .execute()
    # )
    #
    # if not match.data:
    #     return None
    #
    # task_id = match.data["task_id"]
    #
    # similarity_score = float(
    #     match.data["similarity_score"]
    # )
    # ======================================================

    ## parita chauhan 7-15-2026 , start 

    # ----------------------------------------
    # Fetch Employee Name
    # ----------------------------------------

    employee = (
        supabase
        .table("employee_profiles")
        .select("name")
        .eq("emp_id", emp_id)
        .single()
        .execute()
    )

    employee_name = employee.data["name"]  

    # parita chauhan 7-15-2026 , end
     
    # ----------------------------------------
    # Fetch Task Details
    # ----------------------------------------

    #task = (
    #    supabase
    #    .table("tasks")
    #    .select(
    #        "starting_date, deadline"
    #    )
    #    .eq("id", task_id)
    #    .single()
    #    .execute()
    #)

    #starting_date = task.data["starting_date"]

    #deadline = task.data["deadline"]
    
    #-----15/07/2026---------------------start------------------ mili add this code 
    task = (
        supabase
        .table("tasks")
        .select("""
            starting_date,
            deadline,
            priority,
            complexity
        """)
        .eq("id", task_id)
        .single()
        .execute()
    )

    task = task.data

    starting_date = task["starting_date"]
    deadline = task["deadline"]
    priority = task["priority"]
    complexity = task["complexity"]
    
    #-----------15/07/2026------------------------end------------------ mili add this code 


    # ----------------------------------------
    # Calculate Workload
    # ----------------------------------------

    result = calculate_employee_scores(
    starting_date,
    deadline,
    similarity_score,
    emp_id,
    task_id
)
    #---------15/07/2026-------------------------start------------------ mili add this code 

    # ----------------------------------------
    # Priority Score
    # ----------------------------------------

    priority_map = {

        "Critical": 100,

        "High": 80,

        "Medium": 60,

        "Low": 40,

        "Very Low": 20

    }
    
    priority_score = priority_map.get(priority, 50)
    
    # ----------------------------------------
    # Complexity Score
    # ----------------------------------------

    complexity_map = {

        "Very Easy": 50,

        "Easy": 60,

        "Medium": 75,

        "Hard": 90,

        "Expert": 100

    }

    complexity_score = complexity_map.get(complexity, 70)
    
     # ----------------------------------------
    # Deadline Urgency
    # ----------------------------------------

    days_left = (

        datetime.strptime(deadline, "%Y-%m-%d")

        -

        datetime.today()

    ).days

    if days_left <= 2:
        urgency_score = 100

    elif days_left <= 5:
        urgency_score = 90

    elif days_left <= 10:
        urgency_score = 80

    elif days_left <= 15:
        urgency_score = 70

    elif days_left <= 20:
        urgency_score = 60

    else:
        urgency_score = 50

    # ----------------------------------------
    # Final Assignment Score
    # ----------------------------------------

    final_score = (

        similarity_score * 0.45

        +

        result["workload_score"] * 0.25

        +

        priority_score * 0.15

        +

        urgency_score * 0.10

        +

        complexity_score * 0.05

    )

    #-----------15/07/2026------------------------end------------------ mili add this code 

    workload_data = {

        "emp_id": emp_id,

        "task_id": task_id,

        "employee_name": employee_name,

        "starting_date": starting_date,

        "deadline": deadline,


        # Store only original task values
        # Score calculation remains internal

        "priority": priority,

        "complexity": complexity,


        "similarity_score": similarity_score,


        "total_days": result["total_days"],


        "total_task_hours":
            result["total_task_hours"],


        "total_weekly_available_hours":
            result["total_weekly_available_hours"],


        "free_hour_before_deadline":
            result["free_hour_before_deadline"],


        "availability_score":
            result["availability_score"],


        "active_tasks":
            result["active_tasks"],


        "task_load":
            result["task_load"],


        "hours_utilization":
            result["hours_utilization"],


        "workload_score":
            result["workload_score"],


        "resource_balancing_score":
            result["resource_balancing_score"],


        "final_workload_score":
            result["final_workload_score"],


        "updated_at":
            datetime.utcnow().isoformat()

    }

    # ======================================================
    # OLD IMPLEMENTATION (COMMENTED)
    # ------------------------------------------------------
    # Previously workload was generated for every
    # Employee × Task recommendation.
    #
    # (
    #     supabase
    #     .table("employee_workload")
    #     .insert(workload_data)
    #     .execute()
    # )
    # ======================================================

    # ----------------------------------------
    # NEW IMPLEMENTATION
    # Store workload ONLY for the selected
    # Employee -> Task assignment.
    # ----------------------------------------

    workload_data["final_workload_score"] = round(final_score, 2)

    supabase.table("employee_workload").upsert(
        workload_data,
        on_conflict="emp_id"
    ).execute()

    result["final_workload_score"] = round(final_score, 2)

    return result
